import type { Metadata } from 'next'
import './globals.css'
import '@rainbow-me/rainbowkit/styles.css'
import { Providers } from './providers'

import { TooltipProvider } from '@/components/ui/tooltip'
import Navbar from '@/components/Navbar'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <TooltipProvider>
            <div className="flex min-h-screen flex-col items-center px-24 py-4">
              <Navbar />
              {children}
            </div>
          </TooltipProvider>
        </Providers>
      </body>
    </html>
  )
}
